### ISSUE TITLE
Extended paper

### ISSUE THREAD

**Issue by pat-alt** [JuliaTrustworthyAI/LaplaceRedux.jl#66]
Rough game plan for turning extended abstract into full paper (@severinbratus to see). Paper is in `paper/`.

- [x] Update docs to close issues #61 #60 #37 
- [x] Make sure `LaplaceRedux` can be used with `CounterfactualExplanations` #7 (add section to paper)
- [ ] Rework MLJ interface (#39) and ensure `LaplaceRedux` can be used with `ConformalPrediction` (add section to paper)
- [x] #67
- [x] #68
- [ ] #69
- [x] #70

**Comment by pat-alt** [comment]
Going with extended abstract instead
